name: Dispatch event

on:
  issue_comment:
    types: [created]

jobs:
  dispatch:
    runs-on: ubuntu-latest
    if: github.event.issue.pull_request && github.event.comment.body == 'create preview'
    steps:
    - name: Get check run ID
      uses: actions/github-script@v6
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          core.info(`Getting PR test here`)
          const pullRequest = await github.rest.pulls.get({
            owner: context.repo.owner,
            repo: context.repo.repo,
            pull_number: context.issue.number
          })
            
          const checkRuns = await github.rest.checks.listForRef({
            owner: context.repo.owner,
            repo: context.repo.repo,
            ref: pullRequest.data.head.ref
          })

          await github.rest.checks.rerequestSuite({
            owner: context.repo.owner,
            repo: context.repo.repo,
            check_suite_id: checkRuns.data.check_runs[0]?.check_suite.id,
          });

          checkRuns.data.check_runs.forEach((checkRun) => {
              github.rest.checks.update({
              owner: context.repo.owner,
              repo: context.repo.repo,
              check_run_id: checkRun.id
            })
          });
          