name: Dispatch event

on:
  issue_comment:
      types: [created]

jobs:
  dispatch:
    runs-on: ubuntu-latest
    if: ${{ github.event.issue.pull_request }}
    steps:
    - name: Dispatch event
      uses: actions/github-script@v3
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |        
          try {
            core.info(`Getting PR #${request.pull_number} from ${request.owner}/${request.repo}`)
            const result = await github.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number
            })

            core.info(`Creating dispatch event.`);
            github.repos.createDispatchEvent({
              owner: context.repo.owner,
              repo: context.repo.repo,
              event_type: 'my_custom_event',
              client_payload: {
                branchName: result.data.head.ref,
              })
          } catch (err) {
            core.setFailed(`Request failed with error ${err}`)
          }
        
