name: Dispatch event

on:
  issue_comment:
      types: [created]

jobs:
  dispatch:
    runs-on: ubuntu-latest
    if: ${{ github.event.issue.pull_request }}
    steps:
    - name: Dispatch event
      uses: actions/github-script@v3
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          console.log("TEST");
          const request = {
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number
            }
            core.info(`Getting PR #${request.pull_number} from ${request.owner}/${request.repo}`)
            try {
              const result = await github.pulls.get(request)
              core.info(`result data is ${result}`);
              return result.data
            } catch (err) {
              core.setFailed(`Request failed with error ${err}`)
            }

          github.repos.createDispatchEvent({
            owner: context.repo.owner,
            repo: context.repo.repo,
            event_type: 'my_custom_event',
            client_payload: {
              branchName: process.env.BRANCH_NAME,
            }
          })

          // Create check run with status and conclusion
          await github.checks.create({
            owner: context.repo.owner,
            repo: context.repo.repo,
            name: 'Build status',
            head_sha: context.sha,
            status: 'in_progress',
            conclusion: 'neutral',
            output: {
              title: 'Build in progress',
              summary: 'The build is currently in progress.'
            },
            pull_requests: [{ number: context.payload.issue.pull_request.number }]
          })
