name: Dispatch event

on:
  issue_comment:
      types: [created]

jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:
    - name: Dispatch event
      uses: actions/github-script@v3
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |

          console.log("issue pr",context.issue.pull_request);
          console.log("pr head ref",context.issue.pull_request.head.ref);

          github.repos.createDispatchEvent({
            owner: context.repo.owner,
            repo: context.repo.repo,
            event_type: 'my_custom_event',
            client_payload: {
              branchName: context.issue.pull_request.head.ref,
            }
          })

          // Create check run with status and conclusion
          await github.checks.create({
            owner: context.repo.owner,
            repo: context.repo.repo,
            name: 'Build status',
            head_sha: context.sha,
            status: 'in_progress',
            conclusion: 'neutral',
            output: {
              title: 'Build in progress',
              summary: 'The build is currently in progress.'
            },
            pull_requests: [{ number: context.payload.issue.pull_request.number }]
          })
          


