name: Site build

# workflow triggers
on:
  pull_request:
    types:
      - closed
    branches:
      - master
  workflow_dispatch:    

concurrency:
  group: ${{ github.ref_name }}
  cancel-in-progress: true
  
# build process
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: logs
      run: |
        sleep 60
        echo ${{ github.ref_name }}
        echo ${{ github.sha }}    