name: Site build

# workflow triggers
on:
  push:
    branches:
      - stage
  pull_request:
    branches:
      - stage
  workflow_dispatch:    
  repository_dispatch:
    types:
      - webhook-stage
# build process
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - name: logs
      run: |
        echo ${{ toJSON(github) }}
        echo ${{ github.ref_name }}
        echo ${{ github.sha }}