name: Site build

# workflow triggers
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  repository_dispatch:
    types:
      - my_custom_event

# Ensures that only one deploy task per branch/environment will run at a time.
concurrency:
  group: ${{ github.ref_name }}
  cancel-in-progress: true

# comment
# build process
jobs:
  pr_commented:
    # This job only runs for pull request comments
    name: PR comment
    # if: ${{ github.event.comment.body == 'create preview' }}
    runs-on: ubuntu-latest
    steps:
      - run: echo Preview created
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - name: Get check run ID
      uses: actions/github-script@v6
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const checkRuns = await github.rest.checks.listForRef({
            owner: context.repo.owner,
            repo: context.repo.repo,
            ref: context.payload.client_payload.branchName
          })

          await github.rest.checks.rerequestSuite({
            owner: context.repo.owner,
            repo: context.repo.repo,
            check_suite_id: checkRuns.data.check_runs[0]?.check_suite.id,
          });

          console.log("Done");

    - name: logs
      run: |
        sleep 10
        echo ${{ github.event.pull_request.base.ref || github.ref_name }}

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: logs
        path: $GITHUB_WORKSPACE/.github/logs/script.log"