name: Site build

# workflow triggers
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  repository_dispatch:
    types:
      - my_custom_event

# Ensures that only one deploy task per branch/environment will run at a time.
concurrency:
  group: ${{ github.ref_name }}
  cancel-in-progress: true

# comment
# build process
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - name: Get check run ID
      uses: actions/github-script@v6
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |

          core.info(`${JSON.stringify(context.payload)}`);

          const checkRuns = await github.rest.checks.listForRef({
            owner: context.repo.owner,
            repo: context.repo.repo,
            ref: context.payload.client_payload.branchName
          })

          core.info(`Found check runs ${JSON.stringify(checkRuns)}`);
          await github.rest.checks.rerequestRun({
            owner: context.repo.owner,
            repo: context.repo.repo,
            check_run_id: checkRuns.data.check_runs[0]?.id,
          });

          console.log("Done");
