name: Site build

# workflow triggers
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:    
  # repository_dispatch:
  #   types:
  #     - webhook-main
# build process
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - name: logs
      run: |
        echo ${{ toJSON(github) }}
        echo ${{ github.ref_name }}
        echo ${{ github.sha }}